package:
  name: orionmdcore
  version: '1.1.1b1'

source:
  path: ../../

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  string: py_0

requirements:
  pin_depends: strict
  build:
    - invoke==1.2.0
    - lxml==4.6.0
    - numpy==1.21.2
    - mdtraj==1.9.6
    - oeommtools==0.1.20
    - openff-toolkit==0.10.0
    - openff-forcefields==2.0.0
    - openmm==7.5
    - openmoltools==0.8.7
    - packmol==20.010
    - parmed==3.2.0
    - pdbfixer==1.6
    - pip==21.1.1
    - pyparsing==2.4.7
    - python==3.7.10
    - pytest==3.10.1
    - setuptools
    - tqdm==4.57.0
  run:
    - invoke==1.2.0
    - lxml==4.6.0
    - numpy==1.21.2
    - mdtraj==1.9.6
    - oeommtools==0.1.20
    - openff-toolkit==0.10.0
    - openff-forcefields==2.0.0
    - openmm==7.5
    - openmoltools==0.8.7
    - packmol==20.010
    - parmed==3.2.0
    - pdbfixer==1.6
    - pip==21.1.1
    - pyparsing==2.4.7
    - python==3.7.10
    - pytest==3.10.1
    - setuptools
    - tqdm==4.57.0
test:
  requires:
    - pytest
#  imports:
#    - orionmdcore

about:
  home: https://github.com/oess/orionmdcore
  license: OpenEye proprietary
  summary: Orion MD core package
   