package:
  name: orionmdcore
version: '0.0.0'

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - lxml
    - python
    - pytest
    - setuptools
    - numpy
    - openmm
    - pdbfixer
    - pyparsing
    - packmol
    - parmed
  run:
    - lxml
    - python
    - pytest
    - setuptools
    - numpy
    - openmm
    - pyparsing
    - packmol
    - parmed

test:
  requires:
    - pytest
  imports:
    - orionmdcore

about:
  home: https://github.com/oess/orionmdcore