package:
  name: orionmdcore
  version: '0.0.0'

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  pin_depends: strict
  build:
    - lxml==4.6.0
    - numpy==1.18.5
    - mdtraj==1.9.3
    - oeommtools==0.1.17
    - openforcefield==0.8.4
    - openforcefields==1.3.0
    - openmm==7.5
    - openmoltools==0.8.7
    - packmol==20.010
    - parmed==3.2.0
    - pdbfixer==1.6
    - pip==21.1.1
    - pyparsing==2.4.7
    - python==3.7.7
    - pytest==3.10.1
    - setuptools
  run:
    - lxml==4.6.0
    - numpy==1.18.5
    - mdtraj==1.9.3
    - oeommtools==0.1.17
    - openforcefield==0.8.4
    - openforcefields==1.3.0
    - openmm==7.5
    - openmoltools==0.8.7
    - packmol==20.010
    - parmed==3.2.0
    - pdbfixer==1.6
    - pip==21.1.1
    - pyparsing==2.4.7
    - python==3.7.7
    - pytest==3.10.1
    - setuptools
test:
  requires:
    - pytest
  imports:
    - orionmdcore

about:
  home: https://github.com/oess/orionmdcore